#!/usr/bin/env bash
#This script displays
#to infinity and beyond indefinitely
#with a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true; do
	echo "To infinity and beyond"
	sleep 2
done
